# Do NOT update manually; changes here will be overwritten by Copier
_commit: d46567f
_src_path: https://github.com/ingadhoc/addons-repo-template.git
description: 'Aeroo Reports for Odoo


    Allows the generation of Aeroo reports'
is_private: false
name: 'Aeroo Reports

    '
odoo_version: 18.0
pre_commit_ignore: []
slug: ''

