# Do NOT update manually; changes here will be overwritten by Copier
_commit: d46567f
_src_path: https://github.com/ingadhoc/addons-repo-template.git
description: Repositoriy for odoo addons of argentinian localization for functionalities
    that are in odoo enterprise. For any argentinan functionality that is not in odoo
    CE (community edition) or odoo EE (odoo enterprise), please refer to https://github.com/ingadhoc/odoo-argentina
is_private: false
name: ADHOC odoo-argentina-ce
odoo_version: 18.0
pre_commit_ignore: []
slug: ''

